### PR TITLE
ci: add trivy

### PR DESCRIPTION
**Pull request by TartanLeGrand**
Add trivy for security report on this project. 🔥 
Ref: https://github.com/aquasecurity/trivy

### CODE REVIEW

**Comment by aureq** [comment]
Finally, if you could rename `trivy.yml` to `trivy.yaml` for consistency that would be great.

**Comment by TartanLeGrand** [comment]
Hello👋 It's good for you ?

**Comment by aureq** [comment]
@TartanLeGrand Thanks for the ping. I'm a bit time poor but I'm hoping to have some time over this coming weekend 🤞

**Comment by aureq** [comment]
closing this PR as artifacthub.io ([link](https://artifacthub.io/packages/helm/cert-manager-webhook-ovh/cert-manager-webhook-ovh)) provides the same functionality. Thank you @TartanLeGrand for the suggestion.

**Pull request closed without merging**
