### PR TITLE
Add hostNetwork configuration option

### PR DESCRIPTION
**Pull request by Kebree**
Allow to change the app port and to deploy in network host mode to answer this issue:
https://cert-manager.io/docs/installation/compatibility/#aws-eks

### CODE REVIEW

**Comment by aureq** [comment]
Thank you for the PR. Could you please describe the use case for exposing the webhook to the host network?

**Comment by Kebree** [comment]
Hello, like my link says, when you install a custom CNI on AWS EKS (like antrea, calico, or any non-native CNI), you cannot join the control plane into the CNI.
And then, the control plane, not being part of the same network as the webhook is unable to contact it unless you expose a direct port from the service on the port. Hence the hostNetwork mode.
More information and a lot better explanation can be found here : 
https://medium.com/@denisstortisilva/kubernetes-eks-calico-and-custom-admission-webhooks-a2956b49bd0d

**Comment by aureq** [comment]
Sounds good to me.

I think though there's some rework to be done on the template as having 2 dangling properties in the yaml isn't the right way I think.

I may not merge this PR directly but I think it should land inside the chart at some point.

**Comment by Kebree** [comment]
I agree, but I tried to mimic the other charts to have a certain coherence, and they put this configuration on the root of the concerned section. 
For example : 
https://github.com/cert-manager/cert-manager/blob/4cb885a41ec536ea65c75dca9b7208a38c30ce90/deploy/charts/cert-manager/values.yaml#L393

**Comment by aureq** [comment]
Thanks @Kebree for you latest changes.

Yes, it's never simple to keep things coherent. different repositories have different ways of doing things.

**Pull request merged**
